name: Blazing fast GitHub Pages deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: npm install, test and build
        run: |
          npm install static-site
          npm run build
      - name: Commit files
        run: |
          git config --local user.email "MrMondego@users.noreply.github.com"
          git config --local user.name "MrMondego"
          git commit -a -m "Updates"
      - name: Deploy site to gh-pages branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          force: true
